### PR TITLE
fix: handle filenames starting with a dot in getFileParts function

### LINKED ISSUE #389: [Bug] No full screen mode on vanilla Steam Deck
Fullscreen view mode on Steam Deck using vanilla SteamOS not working.

Blank screen with single line instead:

`Error: TypeError: undefined is not an object (evaluating ‘a[0].toUpperCase’).`

### PR DESCRIPTION
**Pull request by je-sendra**
Fixes #389

### CODE REVIEW

File: packages/client-web/src/lib/utils.tsx [hunk 1]
```diff
@@ -49,6 +49,16 @@ export function getFileParts(path: string) {
   const filename = path.split("/").pop() ?? "";
   const parts = filename.split(".");
 
+  // After obtaining the file name without its extension,
+  // if the obtained "stub" is empty, return the whole filename
+  // This fixes an issue where file names starting with a dot (e.g. ".DS_Store")
+  // would crash the application
+  if (parts.length > 0) {
```
Comment (JMBeresford) [inline packages/client-web/src/lib/utils.tsx:56]: I think we need to still handle cases such as `.my_hidden_dot_file.txt` with the current implementation
```suggestion
  if (parts.length === 2) {
```

**Review by JMBeresford — CHANGES_REQUESTED** [review]

File: packages/client-web/src/lib/utils.tsx (hunk 1 above)
Comment (je-sendra) [reply packages/client-web/src/lib/utils.tsx:56]: That implementation would crash with filenames that have no dots (e.g. "README"), let me change it to handle those 2 cases separately

File: packages/client-web/src/lib/utils.tsx [hunk 2]
```diff
@@ -49,6 +49,16 @@ export function getFileParts(path: string) {
   const filename = path.split("/").pop() ?? "";
   const parts = filename.split(".");
 
+  // After obtaining the file name without its extension,
+  // if the obtained "stub" is empty, return the whole filename
+  // This fixes an issue where file names starting with a dot (e.g. ".DS_Store")
+  // would crash the application
+  if (parts.length == 2) {
```
Comment (JMBeresford) [inline packages/client-web/src/lib/utils.tsx:56]:
```suggestion
  if (parts.length === 2) {
```

**Review by JMBeresford — APPROVED** [review]
Just this one nit, otherwise I think we are good to go! Thanks!
